spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bs?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      prefix:
        classpath: /templates
      cache: false #开发时关闭缓存，不然没法看到实时页面
server:
  port: 8081
  servlet:
    context-path: /


